name: MAUI Unit Tests
 
on:
  push:
    branches:
      - main
      - infra/runner-toevoegen
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop
 
jobs:
  test:
    runs-on: macos-latest  # Of windows-latest/macOS-latest als specifiek platform nodig is
    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4
 
      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Gebruik de juiste versie voor MAUI
 
      # Installeer workloads 
      - name: Install MAUI iOS workload
        run: dotnet workload install ios
     
      # Restore dependencie
      - name: Herstel afhankelijkheden
        run: dotnet restore Grocery.App/Grocery.App.csproj
 
      - name: Bouw de applicatie
        run: dotnet build Grocery.App/Grocery.App.csproj -c Release -f net8.0-ios -r iossimulator-x64
 
      - name: Voer unit tests uit
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
